apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
spec:
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: wp-service
          servicePort: 80
